[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
[context.production]
  command = "gatsby build"
[context.deploy-preview]
  command = 'gatsby build && echo -e "/*\n  Basic-Auth: $BASIC_AUTH_ID:$BASIC_AUTH_PASS" > public/_headers'
